name: Terraform CD - Dev

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

concurrency:
  group: terraform-dev
  cancel-in-progress: false

jobs:

  terraform-plan:
    name: Terraform Plan - Dev
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: environments/dev

    steps:

      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.9.8

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_ACTIONS }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false -no-color -var-file=dev.tfvars -out=tfplan

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v5
        with:
          name: terraform-dev-plan
          path: environments/dev/tfplan
          retention-days: 7


  terraform-apply:
    name: Terraform Apply - Dev
    needs: terraform-plan
    runs-on: ubuntu-latest

    environment:
      name: development

    defaults:
      run:
        working-directory: environments/dev

    steps:

      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.9.8

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_ACTIONS }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init -input=false

      - name: Download Terraform Plan
        uses: actions/download-artifact@v6
        with:
          name: terraform-dev-plan
          path: environments/dev

      - name: Terraform Apply
        run: terraform apply -input=false tfplan
